apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: testquarkus0604 
  janus-idp.io/tekton: testquarkus0604
  backstage.io/kubernetes-id: testquarkus0604
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: testquarkus0604
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml