apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testquarkus0604
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testquarkus0604 
  name: testquarkus0604
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testquarkus0604 
